### ISSUE TITLE
Search button broken

### ISSUE THREAD

**Issue by Isuriv** [InsightfulSummer/alphaLib-web#22]
The search button on layouts/search.vue is not working. Need to update its url dynamically and then update the router. Alternatively, we could just get rid of the search button because the search bar should work without it anyway.

**Comment by Isuriv** [comment]
Will try @click.native for the <v-btn> tag because I read that there's problems using v-btn and only @click, alternatively I could just use a <button>. Will update this after trying it out.

**Comment by anewage** [comment]
If you want to put a link, please sue `<nuxt-link>` instead of `<a>`: https://nuxtjs.org/api/components-nuxt-link/

**Comment by anewage** [comment]
BTW, if the pressing "enter" works on the searchbar, not using a button on either cases should be fine. The goal is to have some method of sending the request and viewing the results. We can enhance the component as we move forward.

Please only post the errors and problems that are actually causing an "issue".
I closed #23 since there was not much to say and it was only a status update.

**Comment by anewage** [comment]
Closing this since it is redundant. Please continue the discussion in #2
